// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

function createDisabledClient() {
  return new Proxy(
    {},
    {
      get() {
        throw new Error(
          "Supabase is disabled (missing VITE_SUPABASE_URL / VITE_SUPABASE_PUBLISHABLE_KEY). This project is now configured to use backend (NeonDB) auth."
        );
      },
    }
  ) as unknown as ReturnType<typeof createClient<Database>>;
}

export const supabase = SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY
  ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
      },
    })
  : createDisabledClient();